DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON (
  ID              CHAR(36)        not null,
  FIRST_NAME VARCHAR(250) ,
  LAST_NAME VARCHAR(250) ,
  ADRESS VARCHAR(250) ,
  BIRTH_DATE DATE,
  SALARY NUMBER(19),
  RECORDING_DATE DATE ,
  LEAVING_DATE DATE,
  STATUS     NUMBER(1),

  primary key (ID)
);
